apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
spec:
  serviceName: "storage"
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: gcr.io/icai2025/storage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /phrase
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 2
          volumeMounts:
            - name: storage-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  selector:
    app: storage
  clusterIP: None
  ports:
    - port: 3000
      targetPort: 3000
