apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/icai2025/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: STORAGE_SVC
              value: ""
          livenessProbe:
            httpGet:
              path: /phrase
              port: 3000
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
